### ISSUE TITLE
#3 Give access to settings

### ISSUE THREAD

**Issue by LeandroAntunez** [8i8/ticTacToe#3]
When i executed the program, this asked me to press the enter key, and after that the game just started, without an previous menu. This is highlighted in a to-do's list:

_[src/main.c](https://github.com/8i8/ticTacToe/blob/master/src/main.c) lines 28-33_

` /* TODO `
` * ...`
` *  - Give access to settings.
` * ...`
 `*/`

I can solve this adding an menu after press the enter key! The menu may have the options: Play, Settings, [Help](https://github.com/8i8/ticTacToe/issues/2) and [Quit](https://github.com/8i8/ticTacToe/issues/4).
@8i8  What do you think?

**Comment by 8i8** [comment]
I think this comment is an old one, that I had developed this feature but that essentially the game play is only ever interesting  when you do not know what level the AI is playing at; There are 5 if I remember correctly. Setting this really took out the only interesting part of the game.

**Comment by LeandroAntunez** [comment]
Okay, then a settings feature will not be necessary.
