### ISSUE TITLE
#4 Quit the game

### ISSUE THREAD

**Issue by LeandroAntunez** [8i8/ticTacToe#4]
In order to quit the game, you have to kill the program. This issue is in a to-do list:

_[src/main.c](https://github.com/8i8/ticTacToe/blob/master/src/main.c) lines 28-33_

` /* TODO `
` * ...`
` *  - Add a way for players to quit whilst the game is running. `
` * ...`
` */`

I propose solve this issue adding an interactive way to quit the game, either with a command on the keyboard, as well as in a [menu](https://github.com/8i8/ticTacToe/issues/3).

@8i8 what do you think about those ideas?

**Comment by 8i8** [comment]
That sounds like a great idea; A 'q'  key to quit or something like that.

**Comment by LeandroAntunez** [comment]
[Pull request](https://github.com/8i8/ticTacToe/pull/7) merged.
