### ISSUE TITLE
#5 End the game when stalemate is inevitable

### ISSUE THREAD

**Issue by LeandroAntunez** [8i8/ticTacToe#5]
When the game is destined to end in a standstill, anyway the play have to continue. Prior a solution to this "situation" is highlighted in a to-do's list:

_[src/main.c](https://github.com/8i8/ticTacToe/blob/master/src/main.c) lines 28-33_

` /* TODO `
` * ...`
` *  - Automatic game end when stalemate is inevitable.
` * ...`
 `*/`

This task can be the most challenging, but not imposible. Require have full knowledge about the code and the IA behavior. In reward, the user can have an more fluid and intuitive experience!

@8i8 What do you think about this feature? i'll manage to solve it!

**Comment by 8i8** [comment]
It should not be hard to add as I was only thinking of the real terminal cases where there are only three moves left and loosing is inevitable and for this only the case when the player will lose, we all like to play every move for a win. With that said, considering my comment on the settings page; This could be a setting that may irritate some and it be worth having the possibility of adjusting it; A settings or an instructions page should be visited only when a specific key is pressed, forcing a player to go through them every time would be a little irritating I think. After a little reflection I think that what I had in mind was only to stop the filling in by the computer of the last square when it wins, and the line draw.

So there are differing levels of complexity to it as a feature,  similar in ways to another feature that needs to be added to the AI to improve the game play's intelligence, to add another level to it as it were. Not sure how to explain this off hand, probably better for some other time.

**Comment by LeandroAntunez** [comment]
So, from what I understood, the idea is that the player can configure if the last (last three, or the last) movements can be omitted in the event that the AI ​​will inevitably win that game. This is correct?
