### ISSUE TITLE
Game needs an ending display, a prize.

### ISSUE THREAD

**Issue by 8i8** [8i8/ticTacToe#6]
The game currently ends by segfaulting when you get to 17 bars in the score display; I intend some day to make a short animation for the win; Not got round to it yet, do feel free to amuse your self here if you would like. Best I think to make a sketch of an idea before coding it for discussion as to the overall effect desired.

**Comment by LeandroAntunez** [comment]
That seems to be a nice idea! I'll let you know if i can think of something.

**Comment by LeandroAntunez** [comment]
How about an fireworks screen, with an "congratulations" in the middle or something? Example:

![demo-fireworks](https://user-images.githubusercontent.com/19518791/60685581-2f672b80-9e7a-11e9-8638-18adca1d66ac.gif)
