### ISSUE TITLE
Internationalisation should not break the Makefile.

### ISSUE THREAD

**Issue by 8i8** [8i8/ticTacToe#8]
I did not pay enough attention to the application of the language modification, we will need to find a way to build that is driven by the Makefile, under no circumstances can the Makefile be a binary file.

**Comment by LeandroAntunez** [comment]
We can leave the Makefile as it was before the internationalization modification, that will not change the base program, or the latest updates, and it will be able to continue changing the languages. I agree that the Makefile cannot be a binary file.
